### ISSUE TITLE
IndexError when sending a transaction from the Vault

### ISSUE THREAD

**Issue by lamat1111** [SatoriNetwork/Neuron#17]
# IndexError Report: Empty List in Wallet Transaction

## Summary

An IndexError is occurring when trying to pop an item from an empty list. This is happening in the `_gatherCurrencyUnspents` method of a wallet object. The issue suggests that the wallet is trying to gather unspent currency transactions, but there are no unspent transactions available.

The root cause appears to be in the `sendSatoriTransactionFromVault` function, which is likely attempting to send a transaction without having any available funds (unspent transactions) to use. 

**Note:** The wallet where this was tested reportedly has funds.

## Error Details

```
IndexError: pop from empty list
```

### Traceback

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask-3.0.0-py3.9.egg/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask-3.0.0-py3.9.egg/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/Flask_Cors-4.0.0-py3.9.egg/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask-3.0.0-py3.9.egg/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask-3.0.0-py3.9.egg/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/Flask_Cors-4.0.0-py3.9.egg/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask-3.0.0-py3.9.egg/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask-3.0.0-py3.9.egg/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Satori/Neuron/satorineuron/web/app.py", line 200, in decorated_function
    return f(*args, **kwargs)
  File "/Satori/Neuron/satorineuron/web/app.py", line 601, in sendSatoriTransactionFromVault
    result = sendSatoriTransactionUsing(start.vault, network, 'vault')
  File "/Satori/Neuron/satorineuron/web/app.py", line 689, in sendSatoriTransactionUsing
    return accept_submittion(sendForm)
  File "/Satori/Neuron/satorineuron/web/app.py", line 635, in accept_submittion
    result = myWallet.typicalNeuronTransaction(
  File "/Satori/Lib/satorilib/api/wallet/wallet.py", line 1499, in typicalNeuronTransaction
    result = self.satoriTransaction(amount=amount, address=address)
  File "/Satori/Lib/satorilib/api/wallet/wallet.py", line 880, in satoriTransaction
    gatheredCurrencySats) = self._gatherCurrencyUnspents(
  File "/Satori/Lib/satorilib/api/wallet/wallet.py", line 655, in _gatherCurrencyUnspents
    smallestUnspent = unspentCurrency.pop(0)
IndexError: pop from empty list
```

## Additional Information

The debugger caught an exception in the WSGI application. You can now look at the traceback which led to the error. To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback, you can also create a paste of it.

**Comment by lastmeta** [comment]
I believe this has been solved. if you can get it again, please let us know

**Comment by lamat1111** [comment]
Yes, I haven't had this issue on latest neuron versions. Thank you!
